### ISSUE TITLE
【iOS】13.7から結果ファイルの表示形式が変わるかも？な件

### ISSUE THREAD

**Issue by teriha8t8** [openCACAO/cocoa-issues#16]
iOS14βの情報はAppleにフィードバックして他には出さないことになってるんですが、
大きく変わりそうだとそうもいってられないので公開。
(TweetはダメだったけどGitHubもダメだっけ？後で調べてみます(ぇ))
![IMG_0035](https://user-images.githubusercontent.com/70134832/91558250-f5f05a00-e970-11ea-88e9-a729673004bf.PNG)

これがiOS14β6の結果ファイルです。
ハッシュ値は本日付のZIP13本分揃ってます。
ハッシュ値をタップすれば今と同じ接触チェックファイル詳細がでます。

この形式だと、エントリー100本かつ今のZIPの落ち方で2週間分の結果ファイルを保持できます。

2週間分の結果ファイルを保持できるように、というのはドイツからAppleへ強く要望されていた案件です。
なので、この形式が13.7から採用される可能性は高いと感じます。

アプリに照合結果が反映されるなら歓迎すべき変更仕様ですが、今の日本でこれをやられると、ツールとして紹介しているショートカット他が使えなくなります。
ハッシュ値さえあればわかりはしますが、通知を受けたユーザーは13本のファイルを点検するしかないですね…。

**Comment by rocaz** [comment]
こちら、13.7もリリースされ最大の懸念だったショートカットも更新して頂いたので、クローズにしていいですか？

**Comment by teriha8t8** [comment]
はい、クローズしてください。
