### ISSUE TITLE
【共通】1人で2台アプリを運用している時の陽性登録

### ISSUE THREAD

**Issue by ghost** [openCACAO/cocoa-issues#20]
社用スマホとプライベートのスマホ両方に
接触確認アプリをインストールして使っていた場合、
処理番号はどの様に入力するのか。

システム上、未対応？
運用上どの様にする？

HER-SYSからは"1人1つの処理番号"が発行されるはず。
その処理番号は"1度きりしか利用出来ない"はずである。

企業での社用スマホへの導入も増えつつあり
今後はこの様な陽性者の方も増えると予想される。

アプリのサポートへ質問中。

**Comment by rocaz** [comment]
@sumo-sumo 多分サポートからはまだ返答無いのだと思いますが、厚労省Issuesへもそのまま[質問]として転記しておいてはどうでしょう。
公式FAQ含めてこれまで発信されていない質問と思いますし、実際にどちらへ入力するかわからないという利用者は多いように思います。
(実際には普段から「よく」持ち歩いている方であればどれでもいいのでしょうが)

**Comment by ghost** [comment]
@rocaz そうですね。公式の方にも載せてみます。

助言ありがとうございます。

厚労省公式にも登録。
[https://github.com/cocoa-mhlw/cocoa/issues/8](https://github.com/cocoa-mhlw/cocoa/issues/8)

**Comment by ghost** [comment]
現状は1人1つの処理番号につき1端末のみに対応。
1人で複数台運用は今後、開発の参考にしてくれるそうです。

プライベート、社用を同時に持ち歩いてる人の方はプライベートの方で登録。
勤務中は社用のみしか持ち歩かない方は判断に困るけど
自身の行動を振り返って人が集まる様な場所に携帯していた方に登録。
ぐらいしか無さそうですね。

**Comment by rocaz** [comment]
よかったです。
1端末=1自然人扱いにならざるを得ないのでシステム的な対応は難しいのは既知であるはずなので、一般の方や保健所からの案内へきちんと反映してもらいたいですよね。

**Comment by ghost** [comment]
[非公式FAQ17](https://github.com/openCACAO/cocoa-documentation/wiki/%E9%9D%9E%E5%85%AC%E5%BC%8FFAQ#17%E5%85%B1%E9%80%9A1%E4%BA%BA%E3%81%A72%E5%8F%B0%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E9%81%8B%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E6%99%82%E3%81%AE%E9%99%BD%E6%80%A7%E7%99%BB%E9%8C%B2)に記載したのでcloseします。
